### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by c-bata** [kobinpy/wsgi-static-middleware#5]
https://github.com/kobinpy/kobin/tree/master/example/template_and_static_files

```
127.0.0.1 - - [01/Dec/2016 15:52:12] "GET /static/favicon.ico HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 179, in finish_response
    for data in self.result:
  File "/Users/c-bata/PycharmProjects/kobin/venv/lib/python3.5/site-packages/wsgi_static_middleware.py", line 48, in _iter_and_close
    block = file_obj.read(block_size)
  File "/usr/local/Cellar/python3/3.5.1/bin/../Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 14: invalid start byte
127.0.0.1 - - [01/Dec/2016 15:52:12] "GET /static/favicon.ico HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 63594)
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 179, in finish_response
    for data in self.result:
  File "/Users/c-bata/PycharmProjects/kobin/venv/lib/python3.5/site-packages/wsgi_static_middleware.py", line 48, in _iter_and_close
    block = file_obj.read(block_size)
  File "/usr/local/Cellar/python3/3.5.1/bin/../Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 14: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 344, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------

```

**Comment by c-bata** [comment]
https://github.com/kobinpy/wsgi-static-middleware/blob/master/wsgi_static_middleware.py#L48

**Comment by c-bata** [comment]
gunicorn logs

```
$ gunicorn -w 1 app:app
[2016-12-02 11:12:30 +0900] [30024] [INFO] Starting gunicorn 19.6.0
[2016-12-02 11:12:30 +0900] [30024] [INFO] Listening at: http://127.0.0.1:8000 (30024)
[2016-12-02 11:12:30 +0900] [30024] [INFO] Using worker: sync
[2016-12-02 11:12:30 +0900] [30027] [INFO] Booting worker with pid: 30027
[2016-12-02 11:12:38 +0900] [30027] [ERROR] Error handling request /static/favicon.ico
Traceback (most recent call last):
  File "/Users/c-bata/PycharmProjects/kobin/venv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/c-bata/PycharmProjects/kobin/venv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
    for item in respiter:
  File "/Users/c-bata/PycharmProjects/kobin/venv/lib/python3.5/site-packages/wsgi_static_middleware.py", line 48, in _iter_and_close
    block = file_obj.read(block_size)
  File "/usr/local/Cellar/python3/3.5.1/bin/../Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 14: invalid start byte
```

**Comment by c-bata** [comment]
It will raise when return `favicon.ico`

**Comment by kazi-10g80d** [comment]
Having a similar issue
Can you help me ?
Windows 10
python 3.6

```
[27/Apr/2018 03:28:45] "GET /static/admin/css/responsive.css HTTP/1.1" 200 8192
Traceback (most recent call last):
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
[27/Apr/2018 03:28:45] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 180, in finish_r                                                                                   esponse
    self.write(data)
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 332, in send_hea                                                                                   ders
    self.send_preamble()
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 255, in send_pre                                                                                   amble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Users\KaziFarhan\Anaconda3\lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the                                                                                    software in your host machine
[27/Apr/2018 03:28:45] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[27/Apr/2018 03:28:45] "GET /static/admin/css/responsive.css HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51780)
[27/Apr/2018 03:28:45] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
Traceback (most recent call last):
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
[27/Apr/2018 03:28:45] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 20                                                                                   0 82564
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 180, in finish_r                                                                                   esponse
    self.write(data)
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 332, in send_hea                                                                                   ders
    self.send_preamble()
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 255, in send_pre                                                                                   amble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Users\KaziFarhan\Anaconda3\lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the                                                                                    software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "C:\Users\KaziFarhan\Anaconda3\lib\site-packages\django\core\servers\basehttp.                                                                                   py", line 86, in handle_error
    super().handle_error()
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 368, in handle_e                                                                                   rror
    self.finish_response()
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 180, in finish_r                                                                                   esponse
    self.write(data)
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 331, in send_hea                                                                                   ders
    if not self.origin_server or self.client_is_modern():
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 344, in client_i                                                                                   s_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KaziFarhan\Anaconda3\lib\socketserver.py", line 639, in process_requ                                                                                   est_thread
    self.finish_request(request, client_address)
  File "C:\Users\KaziFarhan\Anaconda3\lib\socketserver.py", line 361, in finish_reque                                                                                   st
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\KaziFarhan\Anaconda3\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "C:\Users\KaziFarhan\Anaconda3\lib\site-packages\django\core\servers\basehttp.                                                                                   py", line 154, in handle
    handler.run(self.server.get_app())
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "C:\Users\KaziFarhan\Anaconda3\lib\wsgiref\simple_server.py", line 35, in clos                                                                                   e
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
```

**Comment by c-bata** [comment]
Could you tell me what version of wsgi-static-middleware you use?

**Comment by kazi-10g80d** [comment]
I am using Django 2.0.4
I have not customized the wsgi 
wsgi.py
`
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "Codez.settings")

application = get_wsgi_application()
`

**Comment by c-bata** [comment]
I need to know a version of **wsgi-static-middleware**. Could you paste an output of `pip freeze` ?

**Comment by kazi-10g80d** [comment]
Django==2.0.4
gunicorn==19.7.1
Pillow==5.1.0
pytz==2018.4

**Comment by kazi-10g80d** [comment]
The website is working fine, but when I am going to the admin page the error is coming

**Comment by c-bata** [comment]
It seems the problem you bumped is no relevant to this issue and this repository.

**Comment by kewp** [comment]
Are you using PostgreSQL? It could be caused by a [code page error](https://stackoverflow.com/questions/20794035/postgresql-warning-console-code-page-437-differs-from-windows-code-page-125).

```
C:\>psql -U postgres
psql (10.5)
WARNING: Console code page (850) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
Type "help" for help.

postgres=#
```

Trying setting the code page before you start Django.

```
cmd.exe /c chcp 1252
```
