### ISSUE TITLE
Content Length Mismatch

### ISSUE THREAD

**Issue by c-bata** [kobinpy/wsgi-static-middleware#7]
refs https://github.com/kobinpy/kobin-example/pull/13

![2016-12-04 1 19 32](https://cloud.githubusercontent.com/assets/5564044/20860621/d8c936e8-b9bf-11e6-92ca-565fc5333ae7.png)

**Comment by c-bata** [comment]
```
Start: 127.0.0.1:8000
127.0.0.1 - - [04/Dec/2016 02:04:21] "GET / HTTP/1.1" 200 788
127.0.0.1 - - [04/Dec/2016 02:04:21] "GET /static/css/style.css HTTP/1.1" 200 669
127.0.0.1 - - [04/Dec/2016 02:04:22] "GET /static/js/bundle.js HTTP/1.1" 200 2545157
127.0.0.1 - - [04/Dec/2016 02:04:23] "GET /static/img/favicon.ico HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/handlers.py", line 179, in finish_response
    for data in self.result:
  File "/Users/c-bata/PycharmProjects/kobin-example/venv/lib/python3.6/site-packages/wsgi_static_middleware.py", line 48, in _iter_and_close
    block = file_obj.read(block_size)
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 14: invalid start byte
127.0.0.1 - - [04/Dec/2016 02:04:23] "GET /static/img/favicon.ico HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 64549)
Traceback (most recent call last):
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/handlers.py", line 179, in finish_response
    for data in self.result:
  File "/Users/c-bata/PycharmProjects/kobin-example/venv/lib/python3.6/site-packages/wsgi_static_middleware.py", line 48, in _iter_and_close
    block = file_obj.read(block_size)
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 14: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/Users/c-bata/.pyenv/versions/3.6.0b4/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
```

**Comment by c-bata** [comment]
https://github.com/kobinpy/wsgi-static-middleware/blob/master/wsgi_static_middleware.py#L27-L29

**Comment by c-bata** [comment]
The static files should be opened 'rb' mode.
Maybe default opened mode is 'wb'?
